AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/StringLiterals:
  Enabled: false
  EnforcedStyle: double_quotes

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArguments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "**/*_spec.rb"
